# Patrick Jeffers   Lab03   8/19/2021
# This program uses python turtle graphics to draw patterns and shapes.  The
# assignment is to draw 2 shapes from Ch.2 exercise #15 in the book.

# Load turtle module.
import turtle

# 2 white squares, point to point.
turtle.bgcolor('gray')
turtle.pensize(2)
turtle.fillcolor('white')
turtle.begin_fill()
turtle.left(45)
turtle.forward(100)
turtle.right(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()

# Transparent rectangular prism.
turtle.penup()
turtle.goto(0,-150)
turtle.pendown()
turtle.setheading(0)
turtle.forward(100)
turtle.right(45)
turtle.forward(141)
turtle.right(45)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(45)
turtle.forward(141)
turtle.right(45)
turtle.forward(100)
turtle.right(135)
turtle.forward(282)
turtle.hideturtle()
turtle.penup()
turtle.goto(100,-150)
turtle.pendown()
turtle.setheading(270)
turtle.forward(200)
turtle.penup()
turtle.goto(0,-250)
turtle.pendown()
turtle.setheading(0)
turtle.forward(200)

# Olympic games symbol circles.
turtle.penup()
turtle.goto(-100,0)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(-220,0)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(-340,0)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(-160,-50)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(-280,-50)
turtle.pendown()
turtle.circle(50)

turtle.done()